language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-victorbrobles
  api_key:
    secure: iMlnA6AHAKRJx4t0w4TqrnAgSl/Tkpo2z1dNlBCydHrWEzLlf+/oZU2BTnGVoP79QIkJWrePX0AAk8binxCA7EB7c2KJsWx2Bobrsh8eZvlQBkiDBe9sD3evjBx1G4X7z6OeBy7KxjELwd/716A1wWcQRm2QQLb3uN5l+FxtjjUsbG72KR3yy5GnvrNC2vKeqWGHSqWogFDv7sEtAxKoLgeIbE2cFCXLThkj+BZxPHbEB9EaQO84AtMJ6mFvIq8sDmUeVN2NvByf6wvWDiCyQvQVSEJM3brgF3fcplFFLdD9f4FtScV/ubprttwswCyxt+CVqZhkNXKVkiD/LU2NSLIEy3kU7bwgouUs/DSruLZ+Qyms7amIep1RrQ1elwbTp1Zu0bmSwRaVlP5oKjXxxUraAB1pKAmTyIcewZ42k+KtCS50ySH033QMf75kepL39pmXbYr/63p9SUAnna5em4fTQupcRuZ52saRMQSFEfaCx8pveCybP8zn1GYgSi5gI9tp/kMtzEFgAoBFSC9gjlRpVdjW5lBXsL34SjOOKov6E9R/e7mQ+q7GrtAUDNySmEbQlnlit2OlIqsAymB/EcD0cMhCaNBDdLFSwuAOm38ncfbdOcmHpo9uz1iAS7eAGPiN5/kEc0HiTIEKFq3PMatyEi1DxMEyDfzppbT63cs=
